gemc/source

detector/detector.cc, detector/detector.h
Moved definitions of G4ThreeVectors found in detector.h to detector.cc in function that builds the cut tube geometry.
=> Jrhosk cut tube

fields/field.cc, fields/symmetries/cylindrical.cc
It would be better if it does a hard exit when field interpolation type is not recognized, it's just a warning now. But I am not sure how to do it properly.
It would be nice to add these field tuning parameter as external options, but that need more code change. maybe later?
=> modify and add field feature to create better propagation in field

hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.cc
I had sector and strip indices swapped in attlen array at point where A,B,C coefficients are retrieved.
=> Fix array indexing error

hitprocess/clas12/micromegas/BMT_hitprocess.cc, hitprocess/clas12/micromegas/bmt_strip.cc, hitprocess/clas12/micromegas/bmt_strip.h
Separated constants from code.  Verification of constant values for BMT region 3.
=> Changed BMT strip routine.  

hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ec_hitprocess.h, hitprocess/clas12/ftof_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.h
ec_hitprocess and pcal_hitprocess made consistent with new 'sector,layer,component' structure of CCDB.
=> New CCDB Structure

hitprocess/clas12/ftof_hitprocess.cc
Edits to address Dan's comments.  No functional change.
=> Minor Edits

hitprocess/clas12/dc_hitprocess.cc, hitprocess/clas12/dc_hitprocess.h
dc smearing / inefficiency:
* smearing parameters, including scale, in database
* inefficiency function, including scale, in database
* if a wire is inefficient, its index is negative
=> dc smearing / inefficiency

hitprocess/clas12/ctof_hitprocess.cc
Requested by Dan Carman so form of CTOF and FTOF codes are mirrored as much as possible. PMT gain factors added. Time resolution updated. Some typos removed.
=> Edits to ctof_hitprocess.cc

output/txt_output.cc
=> change txt output with 12 digit precision instead of default 6

hitprocess/clas12/rich_hitprocess.cc, hitprocess/clas12/rich_hitprocess.h
The hit process routine has been updated. Now all the photons are stored and pixel number is assigned so to keep information as if the photons passed or not QE, if they hit deadspace etc.
=> new version of the rich hit

SConstruct, hitprocess/HitProcess_MapRegister.cc, hitprocess/clas12/rtpc_hitprocess.cc, hitprocess/clas12/rtpc_hitprocess.h
This update worked on my local version of gemc with the new detector I have uploaded.
If I didn't forget anything it should be fine for you too. Please, let me know if there is any issue.
=> Changed BONuS by rtpc where necessary

hitprocess/clas12/cnd_hitprocess.cc, hitprocess/clas12/cnd_hitprocess.h
Changes to cnd hitprocess, now handling CCDB constants
=> Pull request CND

hitprocess/clas12/dc_hitprocess.cc, hitprocess/clas12/dc_hitprocess.h
Changed the files: dc_hitprocess.* with respect to the calcultation of the (tdc-) times.
Other files have been left untouched.
=> Distance to time function

hitprocess/clas12/dc_hitprocess.cc
Removed unused variables and included clhep units and checked for compiling
=> New update on dc_hitprocess

src/MPrimaryGeneratorAction.cc
The is a split off from the previous, now closed, pull request.
See the description of the problem and solution in Issue77.
Closes #77
=> Issue77 - Error in Vertex spreading code 

hitprocess/clas12/micromegas/bmt_strip.cc, hitprocess/clas12/micromegas/fmt_strip.cc
check if strip_id is not empty in bmt_ and fmt_strip.cc, otherwise fill it.
=> check if strip_id is not empty in bmt_ and fmt_strip.cc

hitprocess/clas12/dc_hitprocess.cc, hitprocess/clas12/dc_hitprocess.h
=> Include time walk contributions for DC

hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ec_hitprocess.h, output/evio_output.cc, output/evio_output.h, output/outputFactory.h, output/txt_output.cc, output/txt_output.h, sensitivity/HitProcess.h, src/MEventAction.cc
1st version of the implementation of FADC Mode1 for only EC.
For now, it used constant pedestal mean (101) and sigma (2) for all channels.
=> 1st version of FADC Mode1 output implementation in EC

hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ec_hitprocess.h, hitprocess/clas12/pcal_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.h
CCDB table /calibration/ec/timing has been updated as well.
=> TDC calibration constants

hitprocess/clas12/ctof_hitprocess.cc, hitprocess/clas12/ctof_hitprocess.h, hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ftof_hitprocess.cc, hitprocess/clas12/ftof_hitprocess.h, output/evio_output.cc, src/MEventAction.cc
All detector crates are added in the output/evio_output.cc
In the rest of files, there are minor changes, i.e. only code formating
=> CTOF Mode1 output is added

hitprocess/clas12/ft_cal_hitprocess.cc, hitprocess/clas12/ft_cal_hitprocess.h, hitprocess/clas12/ft_hodo_hitprocess.cc, hitprocess/clas12/ft_hodo_hitprocess.h
FT Hodo and FT Calo hit process code was somehow reset to old where chargeTime was 
empty, not it is fixed again
=> FT Hodo and FT Calo

src/MPrimaryGeneratorAction.cc, src/MPrimaryGeneratorAction.h, src/gemc_options.cc
Adding in time offsets for detached vertex events
=> Chloe's pull request 

sensitivity/sensitiveDetector.cc
I added SynRad with procID = 13 to be grouped near Cerenkov and Scintillation.  If you prefer different procID, I am happy to change it.  
Thanks!
=> Added synchrotron radiation to list of process IDs.

changeLog, src/MEventAction.cc, src/MEventAction.h, src/gemc_options.cc
Added FILTER_HADRONS options: when set to 1, do not write events if there are not hadrons. When abs > 99, do not write events if there are no hadrons matching that value.
Also, do not print progress in begin event if evtN hasn't changed.
=> FILTER_HADRONS

hitprocess/clas12/rtpc_hitprocess.cc, hitprocess/clas12/rtpc_hitprocess.h
RTPC hit process modified with new parameters gathered from May 2019 solenoid field map. Output of digitization changed to include Sector, Layer, Component to match output of other detectors in CLAS12.
=> Modified RTPC hit process parameters and bank names.

hitprocess/clas12/micromegas/fmt_strip.cc
It will no longer be compatible with geometry in previous/current coatjava version. It has been validated.
=> Changing the fmt strip position

materials/material_factory.cc
added tritium isotope to material_factory.cc
=> added tritium isotope

SConstruct, hitprocess/HitProcess_MapRegister.cc, hitprocess/clas12/alert/ahdc_hitprocess.cc, hitprocess/clas12/alert/ahdc_hitprocess.h, hitprocess/clas12/alert/myatof_hitprocess.cc, hitprocess/clas12/alert/myatof_hitprocess.h
Basic hitprocess for ATOF and AHDC with "myatof, 2200" and "ahdc, 2300" hit&bank; this version only gives the hit location by sector/superlayer/layer/paddle or cell dgtz variables output. July 2020.
=> ATOF and AHDC detector hitprocess basic version by V. Sergeyeva

materials/material_factory.cc
added gaseous hydrogen material
=> added hydrogen gas material

hitprocess/clas12/htcc_hitprocess.cc, hitprocess/clas12/htcc_hitprocess.h
HTCC smearing added to hit_process.
=> Add HTCC smearing

hitprocess/clas12/alert/ahdc_hitprocess.cc, hitprocess/clas12/alert/myatof_hitprocess.cc
This message is for a pull request concerning ALERT atof and ahdc hitprocess files. They were modified to create digitization outputs using Edep[s] and time[s] MC truth. Also doca calculation available for ahdc, and SiPM to hit distance for atof.
=> Completed hitprocess files using Edep, time step MC info. V.Sergeyeva, Aug 2020

src/MPrimaryGeneratorAction.cc
for issue "feature, quit if wrong pid #68"
=> exit if pid in input file is wrong

utilities/string_utilities.cc
for issue "enhanced text input file format check #164"
=> more strict check on number

utilities/string_utilities.cc
for issue "enhanced text input file format check #164"
=> fix a bug while using scan_number

SConstruct, fields/asciiField.cc, fields/asciiField.h
These changes compile and the indentation is proper.
=> Loading the binary field maps

hitprocess/clas12/ft_cal_hitprocess.cc, hitprocess/clas12/ft_cal_hitprocess.h, hitprocess/clas12/ft_hodo_hitprocess.cc, hitprocess/clas12/ft_hodo_hitprocess.h
Changed time to be saved from TDC (int) to FADC_TIME (double); changed convert_to_precision to return a double
=> Removed TDC from ft cal and hodo; changed with FADC time

hitprocess/clas12/rtpc_hitprocess.cc, hitprocess/clas12/rtpc_hitprocess.h, output/hipoSchemas.cc
1. Read the parameters from CCDB as in coatjava, instead of hard-coded in the hitprocess file.
* The initial run number should be 11 in clasTags to make sure the parameters are read correctly.
2. Fixed the z_shift as in coatjava.
3. Clean up the codes. 
4. Add rtpc Schema to make them load appropriately in the hipo output.
=> Updated rtpc hitprocess and its hipo output

SConstruct, hitprocess/HitProcess_MapRegister.cc, hitprocess/clas12/recoil/recoil_hitprocess.cc, hitprocess/clas12/recoil/recoil_hitprocess.h, hitprocess/clas12/recoil/recoil_strip.cc, hitprocess/clas12/recoil/recoil_strip.h, output/hipoSchemas.cc, output/hipoSchemas.h, output/hipo_output.h
Digitization for RGH recoil detector, including modifications to output/ files and SConstruct to be able to compile correctly. 
Everything is in synch now with the main branch.
=> Digitization for RGH recoil detector
