hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ec_hitprocess.h, hitprocess/clas12/pcal_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.h
1. I added pcConstants class to organize hardwired constants similar to ecConstants.  
2. Renamed some constants.
3. Added new constants for effective velocity.
4. Previous hitprocess did not propagate light along strip.  This has been added for both EC and PCAL.
5. TDC dgtz now corresponds to current online EVIO format (24 ps / count).  EVIO TDC data in composite bank is in ps, not counts, from both 1190 and 1290 TDCs.  This is Sergey's choice.
Plots below show test of these changes.  Top plot shows EC data from forward carriage, bottom panel show GEMC simulation throwing muons from region of target.  Each panel shows U time plotted vs. V strip (as proxy for distance).  Y axis is actually U-V, time difference of U and V in ns.   For example, U22 plot is time difference of U22 PMT and …
=> Ec hit process

hitprocess/clas12/micromegas/FMT_hitprocess.cc, hitprocess/clas12/micromegas/bmt_strip.cc, hitprocess/clas12/micromegas/bmt_strip.h, hitprocess/clas12/micromegas/fmt_strip.cc, hitprocess/clas12/micromegas/fmt_strip.h
Updates the way the stripsIDs are computed during the simulation of an event for micromegas detectors fmt and bmt, due to new geometry.
=> fmt and bmt new stripsID computation

hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ec_hitprocess.h, hitprocess/clas12/pcal_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.h
1. Used GetCalib method of Calibration object to retrieve CCDB tables for attenuation into double vector.
2. Deleted Assignment object (not needed).
3. Remove test for run=-1 and made run=2 default run if -RUNNO switch not used.
=> CCDB Attenuation tables for EC and PCAL

hitprocess/clas12/ftof_hitprocess.cc, hitprocess/clas12/ftof_hitprocess.h
Modified initializeFTOFConstants to fill ftc structure with values from CCDB.  Currently there are no default settings in case of no database.  Below shows geometric mean for panels 1a,b obtained with current values.
=> CCDB constants for ftof_hitprocess

hitprocess/clas12/ctof_hitprocess.cc, hitprocess/clas12/ctof_hitprocess.h, hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/ec_hitprocess.h, hitprocess/clas12/ftof_hitprocess.cc, hitprocess/clas12/ftof_hitprocess.h, hitprocess/clas12/pcal_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.h
ctof_hitprocess.cc now processes CCDB constants in accordance with Dan Carman's documentation.
Coding is similar to ftof_hitprocess.cc.  Time-walk code is implemented but commented out for future use in case corrections to CFD timings are added to CCDB.  
ftof_hitprocess.cc now follows D. Carman's documentation for FTOF, including smearing of ADC and TDC.
Bug fixed in gaussian smearing of single and several photoelectron response in pcal_hitprocess.cc and ec_hitprocess.cc.  This is important mainly when light is attenuated to near the single photoelectron levels.
=> CCDB Functionality in CTOF,FTOF

hitprocess/clas12/ftof_hitprocess.cc
Functional changed from A/(B+C*sqrt(adc)) to A/pow(adc,B) to follow Haiyan's recommendation.
=> Time-walk Parameterization

src/MPrimaryGeneratorAction.cc, src/MPrimaryGeneratorAction.h
The geometry parameters (x,y,z of the center, radiius) are steered by the COSMICAREA card, the height is set to half the radius. The choice of the cylindric geometry is steered from the last field (#5) of the COSMICAREA card: 
- default: " " || "sph" || "sphere" for a sphere
- "cyl" for a cylinder
=> cosmic rays generation inside a cylinder volume

src/MPrimaryGeneratorAction.cc, src/MPrimaryGeneratorAction.h
Generation of neutron cosmic rays:
- The vertical distribution of cosmic neutrons is described by
j(E) dE ~ E^(-gamma)dE with gamma = 2.95 +- 10 
(from a fit of data by several experiments by Ashton et al. (Cosmic rays at ground level (1973), updated by Nature 256, 387 (1975), see picture). 
- The zenith angle dependence is given by: 
I(theta) = I(0)*cos^n(theta) with theta = 3.5 +- 1.2 
(from Heidbreder et al., J. Geophys. Pres. 76, 2905 (1971)) 
Neutrons are selected by the 4th field in the COSMICRAYS data card, corresponding to the type of cosmic ray particle: muon || neutron. Default (null string): muon is selected.
=> generator for neutron cosmic rays

physics/PhysicsList.cc, physics/PhysicsList.h, sensitivity/sensitiveDetector.cc, src/MPrimaryGeneratorAction.cc, src/MPrimaryGeneratorAction.h, src/gemc_options.cc
include radiative muon decay with spin, BR=100%, steered by FORCE_MUON_RADIATIVE_DECAY option. Option values:
Default = 0:
- BR(mu->e+nu+antinu) = 98.6%
- BR(mu->e+nu+antinu+gamma) = 1.4%
- muon spin neglected (GEANT4 default, standard em model default)
Force radiative decay = 1 (or different from zero):
-  BR(mu-> e+nu+antinu+gamma) = 100%
-  muon spin (V-A) decay included
=> Muon radiative decay, BR = 100%

hitprocess/clas12/ec_hitprocess.cc
Code commented out refers to 'distance to PMT' (latt) calculation when layer volumes were used and hit strips were calculated from geometry.  Simulations run with GEMC 2.5 prior to this PR will not have correct light attenuation for EC.
=> Attenuation distance now calculated using strip geometry

hitprocess/clas12/micromegas/fmt_strip.cc, hitprocess/clas12/micromegas/fmt_strip.h
-Reduce the number of variables to define the geometry so that it is much easier to not forget something to update if needed
-Remove the for-loop over the number of electrons created in the drift space, replaced by a binomial distribution shoot once we have computed the likelihood for the strip to get an electron (Only computed in the neighborhood of the closest strip)
=> Update of the fmt stripfinder and hitprocess

physics/PhysicsList.cc
Before this patch, an error is raised when attempting to load an EM physics process e.g LIV instead of STD
=> Fix list of physics processes

SConstruct, fields/asciiField.cc, fields/asciiField.h, fields/fieldFactory.h, fields/mappedField.cc, fields/mappedField.h, fields/symmetries/cartesian_3d.cc
A file fields/symmetries/cartesian_3d.cc and a few files under fields are modified. some details below
// 3D field in cartesian coordinates. Field itself is in cartesian coordinates.
// Dependent on 3 cartesian coordinates (Y, X, Z)
// The values can be loaded from the map in any order as long as their speed is ordered.
// The values are indexed as B1_3D[X][Y][Z],B2_3D[X][Y][Z],B3_3D[X][Y][Z]
// The field is three dimensional, ordered in the class as B1=Bx, B2=By, B3=Bz
//symmetry "cartesian_3D" is for full 3D map
//symmetry "cartesian_3D_quadrant" is for 3D map covering only the 1st quadrant where x>=0 && y>=0
=> add cartesian_3d field support

src/MEventAction.cc, src/MEventAction.h, src/gemc_options.cc
Provides and implements a new command line option:
-SAVE_SELECTED=“&lt;id&gt;, &lt;pid&gt;, &lt;low limit&gt;, &lt;high limit&gt;, &lt;variable&gt;, &lt;directory&gt;”
This tells GEMC to save the RNG state in a file in directory <directory> for events in which there is a hit satisfying:
* Detector ID matches &lt;id&gt; in all digit positions where &lt;id&gt; does not contain ‘x’ AND
* Particle ID is &lt;pid&gt; AND
* &lt;variable&gt; is in the range from &lt;low limit&gt; to &lt;high limit&gt;
&lt;directory&gt; is optional and defaults to the current directory
For example SAVE_SELECTED="7xx10000, 11, 0.0*MeV, 2000*MeV, trackE, ./” saves RNG state in files in the current directory for events in which there was a hit in detectors 70010000, 70110000, 70210000, etc. by an electron with energy …
=> SAVE_SELECTED option to save selected event RNG states

src/MPrimaryGeneratorAction.cc
GeneratePrimaries seg faults at the end of a LUND input file due to failure to check for eof immediately after getline; this fixes it.
=> Fix seg fault at eof of input file

hitprocess/clas12/ec_hitprocess.cc, hitprocess/clas12/pcal_hitprocess.cc
Constants a3,a4 were never used and are being re-purposed for fine-tuning of the time-walk correction in the timing calibration.  These fine corrections are not currently needed in the time walk simulation.
=> PCAL/EC Timing Simulation

output/outputFactory.h
Tested on MacOS Catalina with clang 12, and on ifarm1901 with gcc 9.2.
Relatively harmless changes.
=> Iss188 - Silence the evio deprecated warnings so other warning become visible.

src/dmesg_init.cc
Simple fix changing the commands that are pushed onto the stack to make use that CHECK_OVERLAPS works again.
Note that the string + std::to_string() is a C++11 construct and could be replaced with C++98 if needed.
=> Make CHECK_OVERLAPS=1 work again.

fields/bclas12MappedField.cc, fields/bclas12MappedField.h
The CMAG utilities are implemented for the calculation of the composite field value using the Torus and Solenoid pointers.
=> Composite Field Value Calculation (Binary Maps)

hitprocess/HitProcess_MapRegister.cc, output/hipo_output.h
Data bank names were changed from alrtdc -> ahdc, alrttof -> atof in:
- hitprocess/HitProcess_MapRegister.cc
- output/hipo_output.h
=> fixed the ALERT data banks names to AHDC::adc, ATOF::adc

materials/material_factory.cc, materials/material_factory.h, materials/mysql_materials.cc, materials/sqlite_materials.cc, materials/text_materials.cc, physics/PhysicsList.cc
We would like to incorporate Mie/forward scattering effects in the RICH aerogel, but Mie scattering parameters are not currently handled in the gemc material definition. This PR will aim to add the Mie scattering parameters to the list of optical parameters loaded for a material, and add Mie scattering to the optical physics list.
=> Enable Mie scattering in gemc

hitprocess/clas12/ecal_hitprocess.cc, hitprocess/clas12/ecal_hitprocess.h
o new ccdb calibration tables (ftime,dtime,fveff,dveff,atten)  introduced for pass2 cooking in coatjava 8.5.0.
o new ccdb digitization tables (fthr, deff, ftres, dtres) to simulate hardware thresholds and timing resolution for FADC and TDC
[ecal-gemc-hitprocess-update.pdf](https://github.com/user-attachments/files/17413339/ecal-gemc-hitprocess-update.pdf)
=> ecal_hitprocess update
